hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "config/NCR-Client.json"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/create-client.toml"

[[files]]
file = "config/fabrication/features.ini"

[[files]]
file = "config/fabrication/item_despawn.ini"

[[files]]
file = "config/item_obliterator.json5"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/picturesign.json"

[[files]]
file = "config/quark-common.toml"

[[files]]
file = "config/supplementaries-common.json"

[[files]]
file = "config/tectonic.json"

[[files]]
file = "config/xaero/minimap/client.cfg"

[[files]]
file = "config/xaero/minimap/profiles/default.cfg"

[[files]]
file = "config/xaero/world-map/client.cfg"

[[files]]
file = "mods/accessories.pw.toml"
metafile = true

[[files]]
file = "mods/aero_cam_sync.pw.toml"
metafile = true

[[files]]
file = "mods/aeronauticsvoidseas.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/blaha-replushed.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/bottle-your-xp.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/carpet-extra.pw.toml"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked-forge.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/chunkyborder.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/configurable.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
metafile = true

[[files]]
file = "mods/create-additions-sable-compat.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-dyeable-ropes.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics-lift-patch.pw.toml"
metafile = true

[[files]]
file = "mods/create-aeronautics.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/daisy.pw.toml"
metafile = true

[[files]]
file = "mods/deathlog.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/defaulted-hotkeys.pw.toml"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
metafile = true

[[files]]
file = "mods/easy-shulker-boxes.pw.toml"
metafile = true

[[files]]
file = "mods/easy-villagers.pw.toml"
metafile = true

[[files]]
file = "mods/embeddedcomputer.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/extreme_sound_muffler.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabrication.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/fastback.pw.toml"
metafile = true

[[files]]
file = "mods/faux-custom-entity-data.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
metafile = true

[[files]]
file = "mods/flashfreeze.pw.toml"
metafile = true

[[files]]
file = "mods/flywheel.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/hexal-0.3.1-NEOFORGE-DEVEL-pre-11.jar"

[[files]]
file = "mods/hexcasting-fabric-1.21.1-0.12.0-devel-pre-48.jar"

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
metafile = true

[[files]]
file = "mods/ioticblocks.pw.toml"
metafile = true

[[files]]
file = "mods/item-obliterator.pw.toml"
metafile = true

[[files]]
file = "mods/jade-sable-compat.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/jline4mcdsrv.pw.toml"
metafile = true

[[files]]
file = "mods/kilt.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/mapsyncer-for-xaeroworldmap.pw.toml"
metafile = true

[[files]]
file = "mods/markdown-manual-renewed.pw.toml"
metafile = true

[[files]]
file = "mods/mc2discord.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/moreiotas.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-restrictions.pw.toml"
metafile = true

[[files]]
file = "mods/observable.pw.toml"
metafile = true

[[files]]
file = "mods/offlinecommands.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/picturesign.pw.toml"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/playerheads+.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/quark-oddities.pw.toml"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
metafile = true

[[files]]
file = "mods/quick-access.pw.toml"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
metafile = true

[[files]]
file = "mods/sable-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/sable-forge.pw.toml"
metafile = true

[[files]]
file = "mods/schematicians-goggles.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/shuttfup.pw.toml"
metafile = true

[[files]]
file = "mods/simulated-copycats.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/unloaded-activity.pw.toml"
metafile = true

[[files]]
file = "mods/vs-hose-connectors.pw.toml"
metafile = true

[[files]]
file = "mods/watermedia-binaries.pw.toml"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
metafile = true

[[files]]
file = "mods/world-casting.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
metafile = true
